
spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/archive
#    username: archive_usr
#    password: S%Z)
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/archive
      username: archive_usr
      password: S%Z)
      pool-name: HikariCP
      maximum-pool-size: 10
      connection-timeout: 60000
  servlet:
    multipart:
      max-file-size   : 100MB
      max-request-size: 100MB
      
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.main.vo

server:
  port: 8080
  servlet:
    session:
      timeout: 600
      
logging:
  config: classpath:logback-archive.xml

file:
  path: file/

page:
  limit : 10
  block : 5
  
naver:
  client-id: MUmUiuEZ0YXq5NezC1Ky
  secret: U2ITnhnahA
  

  
---

spring:
  config:
    activate:
      on-profile: dev



