
spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/archive
#    username: archive_usr
#    password: S%Z)
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/archive
      username: archive_usr
      password: S%Z)
      pool-name: HikariCP
      maximum-pool-size: 10
      connection-timeout: 60000

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.main.vo

server:
  port: 8080
        
logging:
  config: classpath:logback-archive.xml

  
---

spring:
  config:
    activate:
      on-profile: dev



